server:
  port: 9090
  servlet:
    context-path: /v1/internet-shop-api

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5555/internet-shop-db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true