version: '3.8'
services:
  postgres-db:
    image: postgres
    container_name: internet-shop-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=internet-shop-db
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"
    volumes:
      - internet-shop-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

volumes:
  internet-shop-data:
    driver: local